on:
  push:
    branches:
    - master

jobs:
  gprPublish:
    name: Publish to GPR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
          scope: '@UweStolz'
      - run: yarn install
      - name: Compile
        run: yarn run tsc -p ./tsconfig.build.json
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}