on:
  push:
    branches:
    - master

jobs:
  npmPublish:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: publish to NPM
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - name: Compile
      run: yarn run tsc -p ./tsconfig.build.json
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
